### ISSUE TITLE
fatal error on complete user report (moodle 2.9)

### ISSUE THREAD

**Issue by danmarsden** [CTANZ/moodle-theme_decaf#22] opened 2015-08-20 00:02 UTC
/report/outline/user.php?id=3&course=2&mode=complete

I haven't traced this completely yet.

Can not find data record in database table course.

Debug info: SELECT \* FROM {course} WHERE id = ?
[array (
0 => 0,
)]
Error code: invalidrecord
Stack trace:
line 1453 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
line 1429 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
line 404 of /theme/decaf/lib.php: call to moodle_database->get_record()
line 363 of /theme/decaf/lib.php: call to theme_decaf_expand_navigation->expand()
line 319 of /theme/decaf/lib.php: call to theme_decaf_expand_navigation->initialise()
line 95 of /theme/decaf/classes/topsettings_renderer.php: call to theme_decaf_expand_navigation->__construct()
line 113 of /theme/decaf/classes/topsettings_renderer.php: call to theme_decaf_topsettings_renderer->navigation_node()
line 113 of /theme/decaf/classes/topsettings_renderer.php: call to theme_decaf_topsettings_renderer->navigation_node()
line 113 of /theme/decaf/classes/topsettings_renderer.php: call to theme_decaf_topsettings_renderer->navigation_node()
line 113 of /theme/decaf/classes/topsettings_renderer.php: call to theme_decaf_topsettings_renderer->navigation_node()
line 21 of /theme/decaf/classes/topsettings_renderer.php: call to theme_decaf_topsettings_renderer->navigation_node()
line 49 of /theme/decaf/lib.php: call to theme_decaf_topsettings_renderer->navigation_tree()
line 18 of /theme/decaf/layout/columns1.php: call to theme_decaf_init()
line 1015 of /lib/outputrenderers.php: call to include()
line 945 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line ? of unknownfile: call to core_renderer->header()
line 1806 of /lib/setuplib.php: call to call_user_func_array()
line 92 of /report/outline/user.php: call to bootstrap_renderer->__call()
line 92 of /report/outline/user.php: call to bootstrap_renderer->header()

**Comment by danmarsden** [comment] 2015-08-20 00:18
If I add the following code:
https://github.com/CTANZ/moodle-theme_decaf/blob/responsive/classes/topsettings_renderer.php#L57
            if (empty($item->key)) {
                continue;
            }
That seems to prevent the fatal error, but I haven't checked to see if that causes any other issues.

**Comment by pauln** [comment] 2015-08-21 03:49
Hi Dan,
The problem is that `$PAGE->add_report_nodes()` (introduced in Moodle 2.9) adds the new node with type `navigation_node::TYPE_COURSE` - which Decaf then attempts to expand as a course node, failing to do so because it doesn't have a valid course ID.

This same issue happens in themes which don't use the Awesomebar too - but because they expand nodes via an AJAX call, it manifests differently: the node in the navigation block shows up as expandable, and if you attempt to expand it, you get the "Can not find data record in database table course" error as an AJAX error.

Changing the type to `navigation_node::TYPE_USER` (or any other leaf-node type, such as `navigation_node::TYPE_CUSTOM`) will fix the issue.  I'm happy to submit a patch to the Moodle tracker to get the type changed; do you have any suggestions as to which node type would be "most correct" in this situation?

**Comment by danmarsden** [comment] 2015-08-21 05:34
Not sure - I'd need to go looking at the code, my first instinct would be that it should be a TYPE_USER - but i still think you should probably add some error checking to decaf to ensure that $item->key is valid before you do too much more with it - there are probably other pages not well defined in various 3rd party plugins.

**Comment by Tigger996** [comment] 2016-08-18 15:26
I'm interested in a fix for this as well.

**Comment by Tigger996** [comment] 2016-09-15 15:48
Has this been fixed in 2.1.1 as well?  It's becoming an issue with most of my teachers.

Thanks

**Comment by pauln** [comment] 2016-09-18 01:14
Sorry - yes, this should also be fixed in 2.1.1.  I've updated the [release notes in Moodle Plugins ](https://moodle.org/plugins/pluginversion.php?id=12216) accordingly.

**Closed as completed by pauln** 2016-09-18 01:14 UTC
